pre commit hook improvement

diff --git a/jdroid-gradle-root-plugin/src/main/resources/scripts/git/pre-commit b/jdroid-gradle-root-plugin/src/main/resources/scripts/git/pre-commit
--- a/jdroid-gradle-root-plugin/src/main/resources/scripts/git/pre-commit
+++ b/jdroid-gradle-root-plugin/src/main/resources/scripts/git/pre-commit
@@ -8,4 +8,10 @@ if [ ! -z "$CHANGED_KT_FILES" ]; then
 
     # save changes back to git commit
     git add $(echo "$CHANGED_KT_FILES" | paste -s -d " " -)
+
+    CHANGED_KT_FILES=$(git diff --cached --name-only)
+    if [ -z "$CHANGED_KT_FILES" ]; then
+        echo -e "\n\nAborting commit. All changes were restored by ktlint\n\n"
+        exit 1
+    fi
 fi
